version: '3.9'

services:
  api:
    build: .
    image: gmoroz/todolist
    command: >
      sh -c "python /code/todolist/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./todolist:/code/todolist/
    ports:
      - 8000:8000
    env_file:
      - .env.docker
    depends_on:
      db:
          condition: service_healthy
      migration:
          condition: service_completed_successfully
  migration:
    build: .
    image: gmoroz/todolist
    command: python /code/todolist/manage.py migrate
    volumes:
      - ./todolist:/code/todolist/
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./frontend
    image: gmoroz/todolist-front
    volumes:
      - frontend:/app/build
    depends_on:
      - db
      - api
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=todolist
      - POSTGRES_PASSWORD=todolist
      - POSTGRES_DB=todolist
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:1.19.3
    ports:
      - 3000:3000
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - db
      - frontend

volumes:
  postgres_data:
  frontend: