version: '3.9'

x-common-variables: &common-variables
  POSTGRES_USER: todolist
  POSTGRES_PASSWORD: todolist
  POSTGRES_DB: todolist

services:
  api:
    build: .
    command: >
      sh -c "python /code/todolist/manage.py collectstatic --noinput
      && python /code/todolist/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env.docker
    volumes:
      - staticdata:/usr/src/app/static_files
    depends_on:
      db:
          condition: service_healthy
      migration:
          condition: service_completed_successfully
  migration:
    build: .
    command: >
      sh -c "python /code/todolist/manage.py migrate"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: sermalenk/skypro-front:lesson-36
    volumes:
      - frontend:/app/build
    ports:
      - 8038:80
    depends_on:
      - db
      - api
  db:
    image: postgres:latest
    environment: 
      *common-variables
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:1.19.3
    ports:
      - 3000:3000
    volumes:
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - db
      - frontend

volumes:
  postgres_data:
  frontend:
  staticdata: