version: '3.9'

services:
  api:
    image: gmoroz/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    command: >
      sh -c "python /code/todolist/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      db:
          condition: service_healthy
      migration:
          condition: service_completed_successfully
  migration:
    image: gmoroz/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    command: >
      sh -c "python /code/todolist/manage.py migrate"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: gmoroz/todolist-front
    volumes:
      - frontend:/app/build
    depends_on:
      - db
      - api
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:1.19.3
    ports:
      - 3000:3000
    volumes:
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - db
      - frontend

volumes:
  postgres_data:
  frontend: