# Generated by Django 4.1.5 on 2023-01-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(default='', max_length=12, verbose_name='код подтверждения'),
        ),
    ]
