# Generated by Django 4.1.5 on 2023-01-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='tg_id',
            new_name='tg_user_id',
        ),
    ]
