# Generated by Django 4.1.5 on 2023-01-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tguser",
            name="cat_choosen",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tguser",
            name="is_creating",
            field=models.BooleanField(default=False),
        ),
    ]
